# Generated by Django 4.1.2 on 2022-11-22 22:07

import account.models
from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator])),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('date_of_birth', models.DateField(default=account.models.return_date_time)),
                ('gender', models.CharField(choices=[('G', 'Gender'), ('M', 'Male'), ('F', 'Female')], default='G', max_length=1)),
                ('phone', models.IntegerField(default=0)),
                ('security_question', models.CharField(choices=[('What Is your favorite book?', 'What Is your favorite book?'), ('What is your mother’s maiden name?', 'What is your mother’s maiden name?'), ('What is your favorite food?', 'What is your favorite food?'), ('What city were you born in?', 'What city were you born in?'), ('Where is your favorite place to vacation?', 'Where is your favorite place to vacation?'), ('What was the first company that you worked for?', 'What was the first company that you worked for?')], default='Active', max_length=100)),
                ('security_answer', models.CharField(max_length=100)),
                ('account_number', models.CharField(default=account.models.random_account, max_length=200, unique=True)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Dormant', 'Dormant'), ('Deactivated', 'Deactivated')], default='Active', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('transaction_pin', models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(4)])),
                ('confirm_transaction_pin', models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(4)])),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profile Update',
            },
        ),
    ]
