# Generated by Django 4.1.2 on 2022-11-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('G', 'Gender'), ('M', 'Male'), ('F', 'Female')], default='G', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_question',
            field=models.CharField(choices=[('What Is your favorite book?', 'What Is your favorite book?'), ('What is your mother’s maiden name?', 'What is your mother’s maiden name?'), ('What is your favorite food?', 'What is your favorite food?'), ('What city were you born in?', 'What city were you born in?'), ('Where is your favorite place to vacation?', 'Where is your favorite place to vacation?'), ('What was the first company that you worked for?', 'What was the first company that you worked for?')], default='Active', max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
