# Generated by Django 4.1.2 on 2022-11-23 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_updateuser_confirm_transaction_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
