# Generated by Django 4.1.2 on 2022-11-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_updateuser_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateuser',
            name='passport',
        ),
    ]
