# Generated by Django 4.1.2 on 2022-11-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_updateuser_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateuser',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
