# Generated by Django 4.1.2 on 2022-11-25 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_updateuser_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateuser',
            name='active',
        ),
    ]
