# Generated by Django 4.1.2 on 2022-11-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_updateuser_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available_balance',
        ),
        migrations.AddField(
            model_name='updateuser',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
