# Generated by Django 4.1.2 on 2022-11-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_user_available_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expenses_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='user',
            name='scheduled_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
