# Generated by Django 4.1.2 on 2023-01-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_user_expenses_balance_user_scheduled_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
    ]
