# Generated by Django 4.1.2 on 2022-11-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
