# Generated by Django 4.1.2 on 2023-01-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_history_description_history_receiver_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='sender_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
