# Generated by Django 4.1.2 on 2022-11-22 22:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_fullname', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('to_account', models.IntegerField()),
                ('transfer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_pin', models.IntegerField(validators=[django.core.validators.MinLengthValidator(4)])),
                ('transfer_description', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Declined', 'Declined')], default='Successful', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Local Tranfers',
            },
        ),
        migrations.CreateModel(
            name='InternationalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_fullname', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_country', models.CharField(max_length=100)),
                ('to_account', models.IntegerField()),
                ('routing_number', models.CharField(max_length=50)),
                ('iban_number', models.IntegerField()),
                ('transfer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency_type', models.CharField(default='USD', max_length=20)),
                ('transaction_pin', models.IntegerField(validators=[django.core.validators.MinLengthValidator(4)])),
                ('transfer_description', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Declined', 'Declined')], default='Successful', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'International Tranfers',
            },
        ),
    ]
