# Generated by Django 4.1.2 on 2022-11-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationaltransfer',
            name='send',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='localtransfer',
            name='send',
            field=models.BooleanField(default=True),
        ),
    ]
