# Generated by Django 4.1.2 on 2022-11-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_internationaltransfer_send_localtransfer_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationaltransfer',
            name='send',
        ),
        migrations.RemoveField(
            model_name='localtransfer',
            name='send',
        ),
    ]
