# Generated by Django 4.1.2 on 2022-11-25 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_internationaltransfer_send_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationaltransfer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='localtransfer',
            name='status',
        ),
    ]
