# Generated by Django 4.1.2 on 2023-01-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_remove_internationaltransfer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationaltransfer',
            name='to_account',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='localtransfer',
            name='to_account',
            field=models.BigIntegerField(),
        ),
    ]
