# Generated by Django 4.1.2 on 2023-01-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_internationaltransfer_to_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationaltransfer',
            name='iban_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='internationaltransfer',
            name='routing_number',
            field=models.BigIntegerField(),
        ),
    ]
