# Generated by Django 4.1.2 on 2023-01-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_alter_internationaltransfer_iban_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtransfer',
            name='to_account',
            field=models.CharField(max_length=150),
        ),
    ]
